"use client";

import Link from "next/link";
import { useState } from "react";
import { Activity, ArrowRight, Bell, Bot, CalendarDays, Check, ChevronDown, CircleGauge, ClipboardCheck, FileChartColumn, FileText, FolderKanban, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings, Sparkles, Users, WandSparkles, Workflow, X } from "lucide-react";
import { agents, leads, moduleData, sections, workflows } from "../data";

const icons: Record<string, React.ElementType> = {dashboard:LayoutDashboard,leads:CircleGauge,discovery:ClipboardCheck,propuestas:FileText,clientes:Users,proyectos:FolderKanban,onboarding:Check,contenido:CalendarDays,reportes:FileChartColumn,aprobaciones:ClipboardCheck,agentes:Bot,automatizaciones:Workflow,configuracion:Settings};
const pageCopy: Record<string,string> = {dashboard:"Prioridades, entregas y decisiones del equipo en tiempo real.",leads:"Captación, calificación y siguiente acción con contexto completo.",discovery:"De respuestas dispersas a un diagnóstico accionable.",propuestas:"Alcance, inversión y validaciones antes de enviar al cliente.",clientes:"Relación, equipo, servicios y salud de cada cuenta.",proyectos:"Ejecución, riesgos, responsables y deadlines visibles.",onboarding:"Todo lo necesario para empezar bien y sin bloqueos.",contenido:"Estrategia, producción y aprendizaje por marca.",reportes:"Datos convertidos en insights y próximos pasos claros.",aprobaciones:"Control humano transversal para cada output sensible.",agentes:"Capacidades, límites y trazabilidad del equipo digital.",automatizaciones:"Recorridos operativos entre datos, IA, sistema y personas.",configuracion:"Workspace, permisos, integraciones y políticas de IA."};
const newActions: Record<string,string> = {leads:"Nuevo lead",discovery:"Nuevo discovery",propuestas:"Nueva propuesta",clientes:"Nuevo cliente",proyectos:"Nuevo proyecto",contenido:"Nueva pieza",reportes:"Nuevo reporte",default:"Crear nuevo"};

function AvansLogo({ compact = false }: { compact?: boolean }) {
  const gradientId = compact ? "avans-gradient-compact" : "avans-gradient";
  return <span className={`avans-logo ${compact ? "compact" : ""}`} aria-label="Avans Agency">
    <svg viewBox="0 0 48 48" role="img" aria-hidden="true">
      <defs><linearGradient id={gradientId} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#f47a34"/><stop offset=".52" stopColor="#cf3f82"/><stop offset="1" stopColor="#8f6adf"/></linearGradient></defs>
      <rect width="48" height="48" rx="12" fill={`url(#${gradientId})`}/>
      <path d="M11 36 21.8 12h5.4L38 36h-6.6l-2-4.8H19.6L17.5 36Zm10.8-10.2h5.4l-2.7-6.5Z" fill="white"/>
    </svg>
    <span><strong>avans</strong>{!compact&&<small>AGENCY OS</small>}</span>
  </span>;
}

export function AgencyOS({section}:{section:string}) {
  const [menu,setMenu]=useState(false); const current=sections.find(s=>s.slug===section)!;
  return <main className="os-shell">
    <Sidebar section={section} open={menu} close={()=>setMenu(false)}/>
    <section className="workspace">
      <Topbar label={current.label} open={()=>setMenu(true)}/>
      <div className="page-content">
        <PageHeader eyebrow={current.group} title={current.label} description={pageCopy[section]} action={newActions[section]||newActions.default}/>
        {section==="dashboard"?<Dashboard/>:section==="leads"?<Leads/>:section==="aprobaciones"?<Approvals/>:section==="agentes"?<Agents/>:section==="automatizaciones"?<Automations/>:section==="configuracion"?<SettingsPage/>:<OperationalModule section={section}/>}
      </div>
    </section>
  </main>;
}

function Sidebar({section,open,close}:{section:string;open:boolean;close:()=>void}) { return <aside className={`sidebar ${open?"open":""}`}>
  <div className="brand"><AvansLogo/><button className="close-menu" onClick={close}><X size={18}/></button></div>
  <button className="workspace-switch"><span className="workspace-logo">A</span><span><strong>Avans Agency</strong><small>Agency OS · Producción</small></span><ChevronDown size={14}/></button>
  <nav>{["General","Comercial","Operación","Entrega","Control","Sistema"].map(group=><div className="nav-group" key={group}><small>{group}</small>{sections.filter(x=>x.group===group).map(item=>{const Icon=icons[item.slug];return <Link onClick={close} href={item.slug==="dashboard"?"/":`/${item.slug}`} className={item.slug===section?"active":""} key={item.slug}><Icon size={16}/><span>{item.label}</span>{item.slug==="aprobaciones"&&<em>7</em>}</Link>})}</div>)}</nav>
  <div className="guardrail"><span><Check size={13}/></span><div><strong>Control humano activo</strong><small>La IA no publica ni cotiza sola</small></div></div>
 </aside> }

function Topbar({label,open}:{label:string;open:()=>void}) {return <header className="topbar"><div className="crumb"><button className="mobile-menu" onClick={open}><Menu size={19}/></button><AvansLogo compact/><b>/</b><strong>{label}</strong></div><div className="top-actions"><button className="global-search"><Search size={15}/><span>Buscar cliente, tarea o proyecto...</span><kbd>⌘ K</kbd></button><button className="icon-button" aria-label="Notificaciones"><Bell size={17}/><i/></button><div className="user"><span>MD</span><div><strong>Manu Díaz</strong><small>Dirección</small></div></div></div></header>}

function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action:string}) {return <div className="page-header"><div><span className="eyebrow">{eyebrow} / Operación</span><h1>{title}</h1><p>{description}</p></div><div className="header-actions"><button><MoreHorizontal size={16}/></button><button className="primary"><Plus size={16}/>{action}<ChevronDown size={14}/></button></div></div>}
function StatusBadge({children,tone="neutral"}:{children:React.ReactNode;tone?:string}) {return <span className={`badge ${tone}`}>{children}</span>}
function StatCard({label,value,meta,tone}:{label:string;value:string;meta:string;tone:string}) {return <article className={`stat-card ${tone}`}><span>{label}</span><strong>{value}</strong><small>{meta}</small></article>}
function SectionHead({title,meta,action}:{title:string;meta?:string;action?:string}) {return <div className="section-head"><div><h2>{title}</h2>{meta&&<p>{meta}</p>}</div>{action&&<button>{action}<ArrowRight size={13}/></button>}</div>}

function Dashboard(){return <><div className="stats"><StatCard label="Pipeline estimado" value="USD 48.2k" meta="↑ 12,8% vs. período anterior" tone="orange"/><StatCard label="Leads activos" value="42" meta="8 requieren seguimiento" tone="magenta"/><StatCard label="Proyectos en curso" value="18" meta="2 con riesgo detectado" tone="lilac"/><StatCard label="Por aprobar" value="7" meta="3 con más de 24 horas" tone="ink"/></div><div className="dashboard-grid">
  <article className="panel span2"><SectionHead title="Foco de hoy" meta="Ordenado por impacto operativo" action="Ver todas las tareas"/><div className="focus-list">{[["Alta","Confirmar alcance y precio · Line Up","Propuesta · Mica","Hoy 12:00"],["Alta","Escalar acceso Meta · Proyecto CRM","Proyecto · Juan","Hoy 15:30"],["Media","Revisar tono de carrusel · Milen","Contenido · Cami","Hoy 17:00"]].map((r,i)=><div key={r[1]}><button className="check">{i===2?<Check size={12}/>:null}</button><StatusBadge tone={i<2?"danger":"warning"}>{r[0]}</StatusBadge><span><strong>{r[1]}</strong><small>{r[2]}</small></span><time>{r[3]}</time></div>)}</div></article>
  <article className="panel"><SectionHead title="Pulso operativo" meta="Últimas 24 horas"/><div className="pulse"><b>86</b><span>/ 100</span><StatusBadge tone="success">Saludable</StatusBadge></div><div className="mini-bars"><span><i style={{width:"92%"}}/>Comercial <b>92%</b></span><span><i style={{width:"78%"}}/>Entrega <b>78%</b></span><span><i style={{width:"88%"}}/>Clientes <b>88%</b></span></div></article>
  <article className="panel span2"><SectionHead title="Pipeline comercial" meta="USD 48.200 ponderados · 19 oportunidades" action="Abrir leads"/><div className="pipeline">{[["Nuevos","11","18.4k"],["Calificados","6","13.8k"],["Discovery","4","8.6k"],["Propuesta","3","7.4k"]].map((x,i)=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>USD {x[2]}</small><i style={{width:`${100-i*18}%`}}/></div>)}</div></article>
  <article className="panel"><SectionHead title="Copiloto Avans" meta="3 señales nuevas"/><div className="ai-note"><WandSparkles size={18}/><p><strong>Hay una oportunidad para actuar.</strong> Line Up respondió el discovery y tiene alto fit. El borrador de propuesta está listo para validar alcance y precio.</p><button>Revisar sugerencia <ArrowRight size={13}/></button></div></article>
 </div></>}

function Leads(){return <div className="module-layout"><article className="panel data-panel"><div className="table-tools"><div><Search size={14}/><input placeholder="Buscar por lead, contacto o servicio"/></div><button>Etapa <ChevronDown size={13}/></button><button>Owner <ChevronDown size={13}/></button><span>5 oportunidades</span></div><div className="table-scroll"><table><thead><tr><th>Lead</th><th>Origen / interés</th><th>Score IA</th><th>Etapa</th><th>Próxima tarea</th><th/></tr></thead><tbody>{leads.map((l,i)=><tr className={i===0?"selected":""} key={l.name}><td><strong>{l.name}</strong><small>{l.contact} · {l.owner}</small></td><td><span>{l.source}</span><small>{l.service}</small></td><td><span className="score">{l.score}</span><small>Fit alto</small></td><td><StatusBadge tone={i===0?"success":"neutral"}>{l.stage}</StatusBadge><small>Falta: {l.missing}</small></td><td><strong>{l.task}</strong><small>{l.budget}</small></td><td><MoreHorizontal size={16}/></td></tr>)}</tbody></table></div></article><DetailPanel title="Milen Muebles" eyebrow="LEAD · SCORE IA 94" facts={[["Contacto","Carolina Méndez · Marketing"],["Origen","Meta Ads → WhatsApp"],["Interés","Pauta + implementación CRM"],["Presupuesto","USD 2.400 / mes"],["Campos faltantes","Decisor final"],["Próxima tarea","Llamar hoy · 16:30"]]} sections={[{title:"Lectura IA",body:"Alta intención, dolor operativo concreto y presupuesto compatible. Conviene validar decisor y plazo antes de avanzar."},{title:"Borrador de respuesta",body:"Hola Carolina, gracias por contarnos el desafío. Podemos ayudarte a ordenar la captación y el seguimiento sin sumar carga al equipo..."}]} action="Enviar a Discovery"/></div>}

function DataTable({columns,rows}:{columns:string[];rows:string[][]}) {return <div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}<th/></tr></thead><tbody>{rows.map((r,i)=><tr className={i===0?"selected":""} key={r[0]}>{r.map((c,j)=><td key={j}>{j===0?<><strong>{c}</strong><small>Actualizado recientemente</small></>:j===2?<StatusBadge tone={i===0?"warning":"neutral"}>{c}</StatusBadge>:c}</td>)}<td><MoreHorizontal size={16}/></td></tr>)}</tbody></table></div>}
function DetailPanel({title,eyebrow,facts,sections,action}:{title:string;eyebrow:string;facts:string[][];sections:{title:string;body:string}[];action:string}) {return <aside className="panel detail-panel"><div className="detail-top"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button><MoreHorizontal size={17}/></button></div><dl>{facts.map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl>{sections.map((s,i)=><section className={i===0?"insight":""} key={s.title}>{i===0&&<Sparkles size={14}/>}<h3>{s.title}</h3><p>{s.body}</p></section>)}<button className="primary full">{action}<ArrowRight size={14}/></button></aside>}
function OperationalModule({section}:{section:string}){const data=moduleData[section];if(!data)return <EmptyState/>;return <div className="module-layout"><article className="panel data-panel"><div className="table-tools"><div><Search size={14}/><input placeholder={`Buscar en ${section}`}/></div><button>Estado <ChevronDown size={13}/></button><button>Responsable <ChevronDown size={13}/></button><span>{data.rows.length} resultados</span></div><DataTable columns={data.columns} rows={data.rows}/></article><DetailPanel {...data.detail}/></div>}

const approvalItems=[["Propuesta","Line Up","Comercial","Proposal Writer","Mica","Alta","1 h 24 min"],["Copy","Milen Muebles","Contenido","Content Engine","Cami","Media","3 h 08 min"],["Reporte","Marzo Pumps","Reportes","Report Analyst","Sofi","Alta","19 h"],["Diagnóstico","Salutaris","Discovery","Discovery Strategist","Juan","Baja","1 día"]];
function Approvals(){return <><div className="approval-summary"><span><b>7</b> pendientes</span><span><b>3</b> prioridad alta</span><span><b>21 h</b> tiempo medio</span><span><b>94%</b> aprobadas esta semana</span></div><div className="approval-grid">{approvalItems.map((a,i)=><article className="panel approval-card" key={a[1]}><header><StatusBadge tone={a[5]==="Alta"?"danger":"warning"}>{a[5]}</StatusBadge><small>Pendiente · {a[6]}</small><MoreHorizontal size={16}/></header><span className="eyebrow">{a[0]} · {a[2]}</span><h2>{a[1]}</h2><p>Generado por <strong>{a[3]}</strong> · Responsable humano: <strong>{a[4]}</strong></p><div className="preview"><Sparkles size={15}/><span><b>Output listo para control</b><small>Contexto y criterios de validación completos.</small></span></div><footer><button>Rechazar</button><button>Pedir ajustes</button><button>Derivar</button><button className="approve"><Check size={14}/>Aprobar</button></footer></article>)}</div></>}
function Agents(){return <div className="agent-grid">{agents.map(a=><article className="panel agent-card" key={a.name}><header><span className="agent-avatar"><Bot size={18}/></span><StatusBadge tone="success">Activo</StatusBadge><button><MoreHorizontal size={16}/></button></header><span className="eyebrow">{a.area}</span><h2>{a.name}</h2><p>{a.goal}</p><dl><div><dt>Datos que usa</dt><dd>{a.data}</dd></div><div><dt>Herramientas</dt><dd>{a.tools}</dd></div><div><dt>Puede sugerir</dt><dd>{a.suggests}</dd></div><div><dt>Límite</dt><dd>{a.limits}</dd></div></dl><div className="agent-metrics"><span><b>{a.runs}</b> ejecuciones</span><span><b>{a.rate}</b> aprobación</span></div><footer><StatusBadge tone={a.alert==="Sin alertas"?"success":"warning"}>{a.alert}</StatusBadge><button>Ver detalle <ArrowRight size={13}/></button></footer></article>)}</div>}
function Automations(){return <div className="workflow-list">{workflows.map(w=><article className="panel workflow-card" key={w.name}><header><div><StatusBadge tone="success">Activa</StatusBadge><h2>{w.name}</h2><p>Disparador: {w.trigger} · {w.runs} ejecuciones</p></div><button>Editar workflow</button></header><div className="workflow-timeline">{w.steps.map((s,i)=><div key={s[0]}><span className={`step-icon s${i}`}>{i===1?<Sparkles size={14}/>:i===3?<Users size={14}/>:i===4?<Check size={14}/>:<Activity size={14}/>}</span><small>{s[0]}</small><strong>{s[1]}</strong>{i<w.steps.length-1&&<i><ArrowRight size={14}/></i>}</div>)}</div></article>)}</div>}
function SettingsPage(){return <div className="settings-grid">{[["Workspace y marca","Logo, identidad, moneda y zona horaria"],["Equipo y permisos","Roles, acceso y responsables humanos"],["Integraciones","CRM, Ads, Analytics y mensajería"],["Políticas de IA","Límites, aprobaciones y trazabilidad"]].map(x=><article className="panel" key={x[0]}><Settings size={18}/><h2>{x[0]}</h2><p>{x[1]}</p><button>Configurar <ArrowRight size={13}/></button></article>)}</div>}
function EmptyState(){return <div className="panel empty"><Bot size={24}/><h2>Preparando este workspace</h2><p>Los datos y acciones aparecerán acá.</p></div>}
