import Link from "next/link";
import { Activity, ArrowRight, CircleAlert, Clock3, Filter, ShieldCheck, UserRoundCheck } from "lucide-react";
import styles from "../audit-health-hub.module.css";

const events = [
  {time:"Hoy · 16:48",actor:"Plataforma 01",area:"Usuarios",action:"Cambió alcance de Cuenta 02",resource:"Grupo Portland · Edinovo",result:"Aplicado",risk:"Baja"},
  {time:"Hoy · 15:22",actor:"Administración 01",area:"Finanzas",action:"Actualizó estado de cobranza",resource:"Epsa · factura demo SEP-024",result:"Aplicado",risk:"Media"},
  {time:"Hoy · 14:51",actor:"Sistema",area:"Seguridad",action:"Bloqueó intento con dominio no autorizado",resource:"Autenticación",result:"Bloqueado",risk:"Alta"},
  {time:"Hoy · 13:06",actor:"Cuenta 01",area:"Clientes",action:"Solicitó acceso financiero temporal",resource:"Epsa · margen y saldo",result:"Pendiente",risk:"Media"},
  {time:"Ayer · 18:14",actor:"Estrategia 01",area:"Benchmark",action:"Validó señal competitiva",resource:"Epsa · automatización",result:"Validado",risk:"Baja"},
];

export function AuditHub(){
 return <div className={styles.page}>
  <section className={styles.hero}><div><span className={styles.kickerLight}>PLATAFORMA · TRAZABILIDAD</span><h1>Cada acción sensible debe poder reconstruirse.</h1><p>Auditoría reúne identidad, acción, recurso, resultado, motivo y evidencia. No es un historial decorativo: sirve para investigar incidentes, revisar decisiones y demostrar qué ocurrió.</p></div><aside><span>DEMO · OCTUBRE 2026</span><strong>Bitácora transversal</strong><p>Los eventos visibles son sintéticos. La persistencia real se implementará junto con autenticación, RLS e integraciones.</p></aside></section>
  <div className={styles.scope}><div><span>QUIÉN</span><strong>Persona, sistema o agente</strong></div><div><span>QUÉ</span><strong>Acción y recurso afectado</strong></div><div><span>POR QUÉ</span><strong>Motivo, aprobación o regla</strong></div><div><span>RESULTADO</span><strong>Aplicado, bloqueado o fallido</strong></div></div>
  <section className={styles.metrics}><a href="#eventos"><span>Eventos demo</span><strong>5</strong><small>3 áreas con actividad hoy</small></a><a href="#eventos"><span>Alta severidad</span><strong>1</strong><small>Intento bloqueado</small></a><a href="#revisiones"><span>Decisiones pendientes</span><strong>1</strong><small>Acceso financiero temporal</small></a><a href="#politica"><span>Retención</span><strong>Por definir</strong><small>Según sensibilidad</small></a></section>
  <section className={styles.block} id="eventos"><header><div><span className={styles.kicker}>BITÁCORA</span><h2>Actividad sensible y cambios materiales</h2></div><p>Filtros por persona, cliente, módulo, acción, severidad, fecha y resultado.</p></header><article className={styles.panel}><div className={styles.panelTitle}><div><span className={styles.kicker}>EVENTOS · DEMO</span><h3>Registro consolidado</h3></div><Filter size={20}/></div><div className={styles.auditHead}><span>Momento</span><span>Actor</span><span>Área</span><span>Acción / recurso</span><span>Resultado</span><span>Riesgo</span></div><div>{events.map((e)=><div className={styles.auditRow} key={e.time+e.action}><div><strong>{e.time}</strong><small>Timestamp</small></div><div><strong>{e.actor}</strong><small>Identidad</small></div><div><strong>{e.area}</strong><small>Módulo</small></div><div><strong>{e.action}</strong><small>{e.resource}</small></div><div><span className={e.result==="Bloqueado"?styles.badgeDanger:e.result==="Pendiente"?styles.badgeWarn:styles.badgeOk}>{e.result}</span></div><div><span>{e.risk}</span></div></div>)}</div></article></section>
  <section className={styles.block} id="revisiones"><header><div><span className={styles.kicker}>INVESTIGACIÓN</span><h2>Del evento a una decisión verificable</h2></div><p>La auditoría debe enlazar solicitud, aprobación, permiso efectivo, uso y revocación.</p></header><div className={styles.twoCol}><article className={styles.panel}><div className={styles.panelTitle}><div><span className={styles.kicker}>CASO ABIERTO · DEMO</span><h3>Acceso financiero temporal</h3></div><CircleAlert size={20}/></div><div className={styles.detailGrid}><div><span>SOLICITANTE</span><strong>Cuenta 01</strong></div><div><span>RECURSO</span><strong>Epsa · margen y saldo</strong></div><div><span>APROBADORES</span><strong>Gerencia + Finanzas</strong></div><div><span>VENCIMIENTO</span><strong>09 oct · 18:00</strong></div></div></article><article className={styles.panel}><div className={styles.panelTitle}><div><span className={styles.kicker}>EVIDENCIA MÍNIMA</span><h3>Qué guarda cada evento</h3></div><ShieldCheck size={20}/></div><div className={styles.stack}>{["ID y timestamp","Actor y tipo de identidad","Acción, recurso y cliente","Resultado y error","Motivo o regla","Aprobación relacionada","Origen: UI, API, workflow o agente","Antes / después cuando corresponda"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div></article></div></section>
  <section className={styles.block} id="politica"><header><div><span className={styles.kicker}>GOBIERNO</span><h2>Retener evidencia sin convertir logs en otro riesgo</h2></div><p>La retención final debe definirse por criticidad y necesidad operativa.</p></header><div className={styles.threeCol}><article className={styles.panel}><Clock3 size={20}/><h3>Retención diferenciada</h3><p>Eventos críticos y financieros pueden requerir más tiempo que actividad operativa común.</p></article><article className={styles.panel}><UserRoundCheck size={20}/><h3>Acceso restringido</h3><p>Leer auditoría también es un permiso.</p></article><article className={styles.panel}><Activity size={20}/><h3>Alertas accionables</h3><p>Los patrones materiales alimentan Seguridad y Salud del sistema.</p></article></div><div className={styles.links}><Link href="/v2/seguridad">Seguridad <ArrowRight size={15}/></Link><Link href="/v2/salud-sistema">Salud del sistema <ArrowRight size={15}/></Link><Link href="/v2/usuarios">Usuarios y roles <ArrowRight size={15}/></Link></div></section>
 </div>
}