import Link from "next/link";
import { Activity, ArrowRight, BellRing, CheckCircle2, CircleAlert, CloudCog, Database, HeartPulse, RotateCcw, ServerCog, Webhook } from "lucide-react";
import styles from "../audit-health-hub.module.css";

const services=[
 {name:"Aplicación web",status:"Operativo",detail:"Preview responde y build completó.",owner:"Desarrollo",check:"HTTP + build"},
 {name:"Base de datos",status:"Pendiente",detail:"Proveedor y métricas productivas aún no conectados.",owner:"Plataforma",check:"Conectividad + capacidad"},
 {name:"Integraciones / APIs",status:"Parcial",detail:"Inventario conceptual disponible; health checks por conexión pendientes.",owner:"Operaciones",check:"Auth + webhook + latencia"},
 {name:"Automatizaciones / jobs",status:"Parcial",detail:"Runs modelados; heartbeat y retry central pendientes.",owner:"Automatización",check:"Último run + errores"},
 {name:"Backups de DB",status:"Definido",detail:"Política diaria; ejecución y restore productivo a validar.",owner:"Plataforma",check:"Última copia + restore"},
 {name:"Storage / archivos",status:"Pendiente",detail:"Necesita estrategia independiente de la base.",owner:"Plataforma",check:"Copia + integridad"},
];

const incidents=[
 ["Media","Integración sin heartbeat","Una conexión externa puede fallar sin señal consolidada.","Operaciones"],
 ["Alta","Restore no probado","Existe política de backup, pero falta simulacro de recuperación.","Plataforma"],
 ["Media","Inventario de secretos incompleto","No todas las credenciales tienen propietario y rotación confirmados.","Seguridad"],
];

export function HealthHub(){
 return <div className={styles.page}>
  <section className={styles.hero}><div><span className={styles.kickerLight}>PLATAFORMA · CONTINUIDAD OPERATIVA</span><h1>Saber que algo falló antes de que lo descubra el equipo.</h1><p>Salud del sistema consolida aplicación, base, integraciones, jobs, backups y capacidad técnica. Cada alerta debe tener impacto, responsable y procedimiento de recuperación.</p></div><aside><span>DEMO · OCTUBRE 2026</span><strong>Estado técnico central</strong><p>Los estados distinguen lo realmente validado de lo definido, parcial o pendiente.</p></aside></section>
  <div className={styles.scope}><div><span>DETECTAR</span><strong>Disponibilidad, errores y degradación</strong></div><div><span>ALERTAR</span><strong>Sólo cuando alguien debe actuar</strong></div><div><span>RECUPERAR</span><strong>Runbook, rollback o restore</strong></div><div><span>APRENDER</span><strong>Causa raíz y prevención</strong></div></div>
  <section className={styles.metrics}><a href="#servicios"><span>Aplicación</span><strong>Operativa</strong><small>Preview validado</small></a><a href="#incidentes"><span>Incidentes demo</span><strong>3</strong><small>1 prioridad alta</small></a><a href="#backups"><span>Backup DB</span><strong>Diario</strong><small>Política definida</small></a><a href="#backups"><span>Restore</span><strong>Pendiente</strong><small>Debe probarse</small></a></section>
  <section className={styles.block} id="servicios"><header><div><span className={styles.kicker}>SERVICE HEALTH</span><h2>Estado por componente crítico</h2></div><p>Un servicio aparece operativo sólo si existe una señal verificable.</p></header><article className={styles.panel}><div className={styles.healthHead}><span>Servicio</span><span>Estado</span><span>Lectura</span><span>Responsable</span><span>Chequeo</span></div><div>{services.map(s=><div className={styles.healthRow} key={s.name}><div><strong>{s.name}</strong><small>Componente</small></div><div><span className={s.status==="Operativo"?styles.badgeOk:s.status==="Pendiente"?styles.badgeWarn:styles.badgeNeutral}>{s.status}</span></div><div><strong>{s.detail}</strong></div><div><strong>{s.owner}</strong></div><div><small>{s.check}</small></div></div>)}</div></article></section>
  <section className={styles.block} id="incidentes"><header><div><span className={styles.kicker}>ALERTAS E INCIDENTES</span><h2>Priorizar por impacto, no por volumen de errores</h2></div><p>Las alertas repetitivas se agrupan. Un incidente necesita severidad, propietario y siguiente acción.</p></header><div className={styles.twoCol}><article className={styles.panel}><div className={styles.panelTitle}><div><span className={styles.kicker}>COLA · DEMO</span><h3>Atención técnica</h3></div><BellRing size={20}/></div><div>{incidents.map(([sev,title,desc,owner])=><div className={styles.incidentRow} key={title}><span className={sev==="Alta"?styles.badgeDanger:styles.badgeWarn}>{sev}</span><div><strong>{title}</strong><p>{desc}</p><small>Responsable · {owner}</small></div></div>)}</div></article><article className={styles.panel}><div className={styles.panelTitle}><div><span className={styles.kicker}>RUNBOOK</span><h3>Qué ocurre cuando algo falla</h3></div><ServerCog size={20}/></div><div className={styles.stack}>{["Detectar y confirmar señal","Clasificar impacto y alcance","Asignar responsable","Contener o degradar con seguridad","Recuperar servicio o datos","Validar flujo principal","Documentar causa raíz y acción preventiva"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div></article></div></section>
  <section className={styles.block} id="backups"><header><div><span className={styles.kicker}>BACKUPS Y RECUPERACIÓN</span><h2>Backup, rollback y restore son capas distintas</h2></div><p>Volver a un deployment anterior no restaura automáticamente base o archivos.</p></header><div className={styles.cardGrid}><article className={styles.smallCard}><Database size={20}/><h3>Base de datos</h3><p>Backup automático diario como política base.</p></article><article className={styles.smallCard}><CloudCog size={20}/><h3>Archivos / storage</h3><p>Copia independiente para documentos y assets.</p></article><article className={styles.smallCard}><RotateCcw size={20}/><h3>Rollback</h3><p>Volver a la aplicación estable ante regresiones.</p></article><article className={styles.smallCard}><CheckCircle2 size={20}/><h3>Restore test</h3><p>Simulacro periódico para comprobar recuperación.</p></article><article className={styles.smallCard}><CircleAlert size={20}/><h3>Antes de cambios críticos</h3><p>Copia adicional antes de migraciones o cambios masivos.</p></article><article className={styles.smallCard}><HeartPulse size={20}/><h3>RPO / RTO</h3><p>Definir pérdida tolerable de datos y tiempo máximo de caída.</p></article></div></section>
  <section className={styles.block}><header><div><span className={styles.kicker}>MONITOREO</span><h2>Qué observar automáticamente</h2></div><p>La frecuencia depende de la criticidad del proceso.</p></header><div className={styles.threeCol}><article className={styles.panel}><Activity size={20}/><h3>Aplicación</h3><p>Uptime, errores, latencia y endpoints principales.</p></article><article className={styles.panel}><Webhook size={20}/><h3>Integraciones</h3><p>Tokens vencidos, webhooks fallidos y rate limits.</p></article><article className={styles.panel}><ServerCog size={20}/><h3>Jobs e IA</h3><p>Última ejecución, retries, errores y consumos anómalos.</p></article></div><div className={styles.links}><Link href="/v2/auditoria">Auditoría <ArrowRight size={15}/></Link><Link href="/v2/seguridad">Seguridad <ArrowRight size={15}/></Link><Link href="/v2/integraciones">Integraciones <ArrowRight size={15}/></Link></div></section>
 </div>
}