export const sections = [
  { slug: "dashboard", label: "Centro operativo", group: "General" },
  { slug: "leads", label: "Leads", group: "Comercial" }, { slug: "discovery", label: "Discovery", group: "Comercial" },
  { slug: "propuestas", label: "Propuestas", group: "Comercial" }, { slug: "clientes", label: "Clientes", group: "Operación" },
  { slug: "proyectos", label: "Proyectos", group: "Operación" }, { slug: "onboarding", label: "Onboarding", group: "Operación" },
  { slug: "brand-brain", label: "Cerebro de Marca", group: "Estrategia" },
  { slug: "contenido", label: "Contenido", group: "Entrega" }, { slug: "produccion", label: "Producción Creativa", group: "Entrega" },
  { slug: "campanas", label: "Campañas", group: "Entrega" }, { slug: "reportes", label: "Reportes", group: "Entrega" },
  { slug: "aprendizajes", label: "Aprendizajes", group: "Estrategia" },
  { slug: "aprobaciones", label: "Aprobaciones", group: "Control" }, { slug: "agentes", label: "Agentes IA", group: "Sistema" },
  { slug: "automatizaciones", label: "Automatizaciones", group: "Sistema" }, { slug: "configuracion", label: "Configuración", group: "Sistema" },
] as const;

export const leads = [
  { name:"Milen Muebles", contact:"Carolina Méndez", source:"Meta Ads", service:"Pauta + CRM", score:94, stage:"Calificado", owner:"Mica", budget:"USD 2.400", missing:"Decisor", task:"Llamar hoy · 16:30" },
  { name:"Line Up", contact:"Tomás Ruiz", source:"WhatsApp", service:"Automatización", score:88, stage:"Discovery", owner:"Juan", budget:"USD 1.800", missing:"Volumen", task:"Discovery · Mañana" },
  { name:"Marzo Pumps", contact:"Laura Viera", source:"Formulario web", service:"Desarrollo web", score:82, stage:"Nuevo", owner:"Sofi", budget:"A validar", missing:"Budget", task:"Calificar · Hoy" },
  { name:"Lonkar Accesorios", contact:"Martín Costa", source:"Instagram", service:"Contenido", score:76, stage:"Seguimiento", owner:"Mica", budget:"USD 1.200", missing:"Timing", task:"Enviar casos · Vie" },
  { name:"Salutaris", contact:"Lucía Soto", source:"Referido", service:"Branding", score:71, stage:"Propuesta", owner:"Juan", budget:"USD 3.100", missing:"—", task:"Follow-up · Lun" },
];

export const moduleData: Record<string, { rows: string[][]; columns: string[]; detail: { title:string; eyebrow:string; facts:string[][]; sections:{title:string; body:string}[]; action:string } }> = {
  discovery:{columns:["Discovery","Lead / cliente","Progreso","Owner","Pendientes"],rows:[["Line Up · Expansión","Line Up","8/10 respuestas","Juan","2 preguntas"],["Marzo Pumps · Web","Marzo Pumps","6/10 respuestas","Sofi","4 preguntas"],["Salutaris · Rebrand","Salutaris","Completo","Mica","Sin pendientes"]],detail:{title:"Line Up · Expansión comercial",eyebrow:"DIAGNÓSTICO IA · V2",facts:[["Relación","Lead: Line Up · Cliente potencial"],["Objetivo","Reducir el tiempo de respuesta comercial"],["Dolor central","Consultas dispersas entre WhatsApp e Instagram"],["Preguntas pendientes","¿Quién valida el pipeline? · ¿Qué CRM usan?"]],sections:[{title:"Oportunidades detectadas",body:"Centralizar captación, priorizar por intención y automatizar el primer seguimiento."},{title:"Servicios recomendados",body:"Automation Sprint · Implementación CRM · Dashboard comercial"}],action:"Generar propuesta"}},
  propuestas:{columns:["Propuesta","Versión","Aprobación interna","Inversión","Actualización"],rows:[["Automation Sprint · Line Up","Borrador IA v3","Revisión Dirección","USD 8.400","Hace 18 min"],["Web Growth · Marzo Pumps","v2","Aprobada","USD 12.600","Ayer"],["Brand System · Salutaris","v1","Ajustes solicitados","A validar","12 ago"]],detail:{title:"Automation Sprint",eyebrow:"BORRADOR IA · V3",facts:[["Diagnóstico","Demoras y pérdida de trazabilidad comercial"],["Solución","CRM, automatización y tablero de gestión"],["Etapas","Discovery técnico · Build · QA · Adopción"],["Entregables","Pipeline, 4 workflows, dashboard y capacitación"],["Exclusiones","Licencias y pauta publicitaria"],["Inversión estimada","USD 8.400 · requiere validación humana"]],sections:[{title:"Alcance",body:"6 semanas de implementación con dos instancias semanales y documentación operativa."},{title:"Próximos pasos",body:"Validación de alcance → precio final → envío al cliente."}],action:"Validar internamente"}},
  clientes:{columns:["Cliente","Servicios","Equipo","Health","Tareas abiertas"],rows:[["Milen Muebles","Pauta · Contenido · CRM","Mica + 3","Saludable","4"],["Line Up","Automation · Web","Juan + 2","Atención","6"],["Marzo Pumps","Web · SEO","Sofi + 2","Saludable","3"],["Lonkar Accesorios","Contenido · Pauta","Mica + 4","Atención","8"],["Salutaris","Branding · Web","Juan + 3","Saludable","2"]],detail:{title:"Milen Muebles",eyebrow:"CLIENTE ACTIVO · DESDE 2024",facts:[["Equipo asignado","Mica (PM) · Vale (Ads) · Cami (Content)"],["Accesos pendientes","Google Analytics · Catálogo Meta"],["Brief de marca","Completo · actualizado 2 ago"],["Documentos","Contrato · Brandbook · Kickoff · 12 archivos"],["Tareas abiertas","4 · una bloqueada"],["Último reporte","Julio · aprobado por cliente"]],sections:[{title:"Servicios contratados",body:"Performance always-on · Content Engine · Optimización CRM"},{title:"Historial reciente",body:"Reporte aprobado · 4 piezas publicadas · acceso solicitado a Analytics"}],action:"Abrir workspace"}},
  proyectos:{columns:["Proyecto","Etapa","Responsable","Deadline","Riesgo IA"],rows:[["Milen · Growth Q3","Optimización","Mica","22 ago","Bajo"],["Line Up · CRM","Implementación","Juan","29 ago","Medio"],["Marzo · Nueva web","Diseño UI","Sofi","12 sep","Bajo"],["Lonkar · Campaña SS26","Producción","Cami","19 ago","Alto"]],detail:{title:"Line Up · Implementación CRM",eyebrow:"PROYECTO · 64% COMPLETO",facts:[["Etapa actual","Integraciones y normalización"],["Responsables","Juan (PM) · Fede (Dev)"],["Deadline","29 agosto · 11 días"],["Bloqueo","Falta acceso de administrador a Meta"],["Tareas","12 completas · 4 abiertas · 1 bloqueada"],["Derivaciones","PM → Desarrollo → Trafficker"]],sections:[{title:"Riesgo detectado por IA",body:"El acceso pendiente puede desplazar QA tres días. Sugerencia: escalar hoy al sponsor."},{title:"Próximo hito",body:"Pruebas end-to-end con el equipo comercial · 23 agosto."}],action:"Ver plan de trabajo"}},
  onboarding:{columns:["Cliente","Progreso","Accesos","Responsable","Kickoff"],rows:[["Salutaris","72%","3 pendientes","Juan","20 ago"],["Marzo Pumps","48%","6 pendientes","Sofi","A coordinar"],["Line Up","91%","1 pendiente","Mica","Completado"]],detail:{title:"Salutaris · Onboarding",eyebrow:"CHECKLIST · 8/11 COMPLETOS",facts:[["Contrato","Firmado"],["Datos fiscales","Completos"],["Accesos","Meta, GA4 y hosting pendientes"],["Brief de marca","En revisión"],["Equipo","Juan · Cami · Fede"]],sections:[{title:"Siguiente acción",body:"Consolidar accesos antes del kickoff del 20 de agosto."}],action:"Solicitar accesos"}},
  contenido:{columns:["Pieza","Marca / pilar","Canal","Estado","Entrega"],rows:[["Carrusel · Living modular","Milen · Inspiración","Instagram","Revisión de tono","Hoy"],["Reel · Ventas sin fricción","Line Up · Educación","Instagram","Diseño","19 ago"],["Caso · Bomba industrial","Marzo · Producto","LinkedIn","Aprobado","21 ago"],["UGC · Nuevos ingresos","Lonkar · Tendencias","TikTok","Copy IA","22 ago"]],detail:{title:"Carrusel · Living modular",eyebrow:"CONTENT ENGINE · BORRADOR V4",facts:[["Marca","Milen Muebles · ficha v3"],["Pilar","Inspiración / espacios reales"],["Formato","Carrusel · 6 placas · Instagram"],["Tono","Cálido, claro, experto sin tecnicismos"],["Aprobación","Pendiente de Content Lead"],["Derivación","Copy → Diseño → Programación"]],sections:[{title:"Copy principal",body:"Tu living no necesita más metros: necesita decisiones inteligentes. Tres formas de ganar espacio sin resignar identidad."},{title:"Prompt visual",body:"Interior argentino contemporáneo, luz cálida lateral, mueble modular como protagonista, paleta neutra, encuadre editorial."},{title:"Prompt de video",body:"Recorrido suave de 8 segundos, reveal del módulo extensible, detalles de textura, cierre con composición completa."},{title:"Aprendizaje de marca",body:"Los ejemplos aprobados usan beneficios concretos. Evitar superlativos y llamados de venta agresivos."}],action:"Enviar a diseño"}},
  reportes:{columns:["Reporte","Fuentes","Período","Revisión","Estado"],rows:[["Milen · Performance","Meta Ads · GA4","Julio","Vale / Mica","Revisión PM"],["Line Up · Comercial","CRM · Analytics","Julio","Juan","Borrador IA"],["Marzo · SEO","Search Console · GA4","Julio","Sofi","Aprobado"]],detail:{title:"Milen · Reporte de julio",eyebrow:"REPORT ANALYST · VERSIÓN CLIENTE",facts:[["Fuentes","Meta Ads · Google Ads · Analytics"],["Carga manual","ROAS offline y ventas del local · completa"],["Capturas interpretadas","4 de Ads Manager"],["Revisión","Trafficker aprobó · PM pendiente"],["Resultado","+18% consultas · -11% costo por lead"]],sections:[{title:"Resumen ejecutivo",body:"La inversión generó más conversaciones calificadas con menor costo. El catálogo fue el principal impulsor."},{title:"Insights",body:"La audiencia de remarketing concentra 38% de las conversiones. Dos creatividades muestran fatiga."},{title:"Próximos pasos",body:"Renovar piezas de catálogo, ampliar test de audiencias y conectar ventas offline."}],action:"Aprobar versión cliente"}},
};

export const agents = [
  ["Lead Classifier Agent","Leads","Priorizar oportunidades por fit."],
  ["Discovery Strategist Agent","Discovery","Convertir respuestas en diagnóstico estratégico."],
  ["Brand Brain Agent","Cerebro de Marca","Consolidar criterios y memoria de marca."],
  ["Creative Strategist Agent","Contenido","Transformar objetivos en conceptos."],
  ["Copywriter Agent","Contenido","Generar copies y variantes de hooks."],
  ["Visual Direction Agent","Producción","Definir dirección y prompts visuales."],
  ["Reel Script Agent","Contenido","Crear guiones breves por canal."],
  ["Design QA Agent","Producción","Validar medidas, marca y completitud."],
  ["Campaign Analyst Agent","Campañas","Detectar alertas y oportunidades de pauta."],
  ["Report Storyteller Agent","Reportes","Traducir métricas a decisiones claras."],
  ["PM Risk Agent","Proyectos","Anticipar bloqueos y riesgos operativos."],
  ["Upsell Opportunity Agent","Reportes","Detectar oportunidades comerciales relevantes."],
].map((a,i)=>({name:a[0],area:a[1],goal:a[2],data:"CRM, Discovery, Brand Brain, métricas e historial",tools:"Análisis · generación · trazabilidad",suggests:"Siguiente acción y output versionado",limits:"No publica, cotiza ni decide sin una persona",approval:"Outputs externos, presupuesto y cambios de alcance",runs:42+i*17,rate:`${88+i%9}%`,alert:i%4===0?"1 revisión pendiente":"Sin alertas"}));

export const engineData: Record<string, {flow:string[]; columns:string[]; rows:string[][]; facts:string[][]; sections:{title:string;body:string}[]; actions:string[]}> = {
  "brand-brain": {flow:["Discovery","Criterios","Revisión humana","Brand Brain","Contenido"],columns:["Cliente","Personalidad","Pilares","Revisión"],rows:[["Milen Muebles","Cálida · experta","Inspiración · Producto","Content Manager"],["Line Up","Ágil · directa","Educación · Casos","Aprobado"],["Marzo Pumps","Técnica · confiable","Industria · Producto","Aprobado"],["Lonkar Accesorios","Audaz · cercana","Tendencias · Comunidad","En revisión"],["Salutaris","Serena · profesional","Bienestar · Educación","Pendiente"]],facts:[["Público objetivo","Familias urbanas que buscan diseño funcional"],["Propuesta de valor","Muebles modulares pensados para espacios reales"],["Diferenciales","Diseño local · modularidad · asesoramiento"],["Objeciones frecuentes","Precio · medidas · tiempo de entrega"],["Palabras recomendadas","espacio · identidad · duradero"],["Palabras prohibidas","barato · imperdible · lujo"],["Estilo visual","Editorial cálido, luz natural, texturas honestas"]],sections:[{title:"Referencias y ejemplos",body:"Aprobado: ambientes reales y beneficios concretos. Rechazado: fondos artificiales y venta agresiva."},{title:"Criterios creativos aprendidos",body:"Mostrar escala humana. Priorizar utilidad antes que tendencia. CTA consultivo."},{title:"Aprendizajes de performance",body:"Los carruseles de distribución de espacios logran 31% más guardados."}],actions:["Generar desde Discovery","Agregar ejemplo aprobado","Agregar ejemplo rechazado","Extraer criterio creativo","Enviar a revisión del Content Manager","Aplicar criterio a nueva pieza"]},
  produccion:{flow:["Brief","Diseño","QA creativo","Aprobación","Programación"],columns:["Pieza","Cliente","Formato / medida","Diseñador","Estado"],rows:[["Living modular","Milen Muebles","Carrusel · 1080×1350","Cami","En revisión"],["Ventas sin fricción","Line Up","Reel · 1080×1920","Nico","En diseño"],["Bomba industrial","Marzo Pumps","LinkedIn · 1200×627","Cami","Aprobada"],["Nuevos ingresos","Lonkar Accesorios","Stories · 1080×1920","Vale","Ajustes"]],facts:[["Canal","Instagram"],["Brief visual","Interior real, luz cálida y producto protagonista"],["Copy asociado","Tu living no necesita más metros"],["Assets necesarios","Fotos ambiente · logo SVG · ficha producto"],["Entrega","Hoy · 17:00"],["Feedback interno","Aumentar contraste del CTA"],["Feedback cliente","Sin comentarios"]],sections:[{title:"Checklist QA",body:"✓ Copy cargado · ✓ Medida correcta · ✓ Logo aplicado · ✓ Coherencia con Brand Brain · ✓ CTA presente · ○ Versión mobile · ✓ Ortografía"}],actions:["Asignar diseñador","Crear checklist QA","Pedir ajustes","Aprobar diseño","Derivar a programación","Registrar bloqueo"]},
  campanas:{flow:["Objetivo","Audiencia","Creatividades","Optimización","Insight"],columns:["Campaña","Cliente","Plataforma","Inversión","Alerta"],rows:[["Catálogo Living Q3","Milen Muebles","Meta Ads","USD 1.840","Fatiga creativa"],["Search Bombas","Marzo Pumps","Google Ads","USD 920","Anuncio ganador"],["Always-on Accesorios","Lonkar Accesorios","Meta Ads","USD 1.210","CPL alto"],["Leads Salud","Salutaris","Google Ads","USD 640","Sin alertas"]],facts:[["Objetivo","Generación de leads"],["Presupuesto","USD 2.400 / mes"],["Audiencia","Remarketing + similares 2%"],["Estado","Activa"],["Alcance / impresiones","84.200 / 191.400"],["Clics / leads","3.210 / 186"],["CPL / CTR","USD 9,89 / 1,68%"],["ROAS","3,4×"],["Responsable","Vale · Trafficker"]],sections:[{title:"Detección IA",body:"Fatiga creativa en dos anuncios. El carrusel modular es ganador. Renovar video y pausar variante B."},{title:"Calidad de lead",body:"El conjunto amplio genera leads baratos, pero 34% menos calificados."}],actions:["Analizar campaña","Generar recomendación","Crear tarea para trafficker","Pedir nueva creatividad","Enviar insight a reporte","Guardar aprendizaje"]},
  aprendizajes:{flow:["Feedback","Reporte","Memoria útil","Brand Brain","Próxima pieza"],columns:["Aprendizaje","Cliente","Origen","Impacto","Estado"],rows:[["Beneficio concreto primero","Milen Muebles","Reporte agosto","Alto","Aplicado"],["Hooks con pregunta","Line Up","Feedback cliente","Medio","Nuevo"],["Producto en contexto técnico","Marzo Pumps","Campaña","Alto","Aplicado"],["Evitar fondos saturados","Lonkar Accesorios","Diseño rechazado","Alto","En revisión"]],facts:[["Contenido que funcionó","Carrusel: 3 formas de ganar espacio"],["Tono aprobado","Cálido, directo y sin superlativos"],["Diseños rechazados","Fondos artificiales sin escala humana"],["Anuncio ganador","Carrusel modular · ROAS 4,1×"],["Objeción frecuente","¿Entra en mi ambiente?"],["Palabras que funcionan","espacio · modular · a tu medida"],["Formato con mejor performance","Carrusel educativo de 6 placas"]],sections:[{title:"Recomendación para próximas piezas",body:"Abrir con un problema espacial reconocible, mostrar escala humana y cerrar con asesoramiento."},{title:"Historial",body:"12 aprendizajes activos · 8 aplicados a contenido · 3 incorporados al Brand Brain."}],actions:["Registrar desde reporte","Registrar desde feedback cliente","Aplicar a nueva pieza","Ver historial por cliente","Enviar al Cerebro de Marca"]}
};

export const workflows = [
  {name:"Captación → Discovery",trigger:"Lead calificado",steps:[["Entrada","Formulario / WhatsApp"],["IA","Clasificar y completar"],["Sistema","Crear oportunidad"],["Humano","Validar fit"],["Salida","Discovery agendado"]],runs:148},
  {name:"Discovery → Propuesta",trigger:"Brief completo",steps:[["Entrada","Respuestas"],["IA","Diagnóstico y alcance"],["Sistema","Versionar borrador"],["Humano","Validar precio"],["Salida","Propuesta lista"]],runs:42},
  {name:"Cliente ganado → Onboarding",trigger:"Propuesta aceptada",steps:[["Entrada","Deal ganado"],["IA","Preparar checklist"],["Sistema","Crear proyecto"],["Humano","Asignar equipo"],["Salida","Kickoff"]],runs:31},
  {name:"Brief → Calendario",trigger:"Marca validada",steps:[["Entrada","Brand brief"],["IA","Pilares e ideas"],["Sistema","Crear piezas"],["Humano","Curar calendario"],["Salida","Diseño"]],runs:76},
  {name:"Métricas → Reporte",trigger:"Cierre mensual",steps:[["Entrada","Ads + Analytics"],["IA","Interpretar datos"],["Sistema","Armar reporte"],["Humano","Revisión PM"],["Salida","Versión cliente"]],runs:54},
  {name:"Aprobación interna → Derivación",trigger:"Output aprobado",steps:[["Entrada","Aprobación"],["IA","Identificar destino"],["Sistema","Actualizar estado"],["Humano","Confirmar owner"],["Salida","Derivación"]],runs:96},
];
